version: 0.1.{build}

branches:
  only:
    - master

cache:
  - packages -> **\packages.config

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore "./Autofac.Eventing.sln"
build:
  project: ./Autofac.Eventing.sln
  verbosity: minimal

test:
  assemblies:
    - '**\*.Tests.dll'

environment:
  COVERALLS_REPO_TOKEN:
    secure: /k35QrSFi+udelJ2UwWp5hB6k2Hp0BIBYc+POQpu8tS7bxGJ4kQ7/m1UQ+9X2OaV

test_script:
- ps: >-
    .\packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -target:nunit-console.exe -register:user "-targetargs:""src/Autofac.Eventing.Tests/bin/$env:CONFIGURATION\Autofac.Eventing.Tests.dll"" /noshadow" -filter:"+[Autofac.Eventing*]*" -output:opencoverCoverage.xml
    .\packages\coveralls.net.0.5.0\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID